# -*- coding: utf-8 -*-
"""calculo_mpi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13PGTz7JDX6K9UQsPtjSLIz_tpZObXoYA
"""

!apt-get update
!apt-get install -y openmpi-bin libopenmpi-dev
!pip install mpi4py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile calculo_mpi.py
# from mpi4py import MPI
# import random
# 
# def main():
#     # 1. Inicialización de MPI
#     comm = MPI.COMM_WORLD
#     rank = comm.Get_rank()
#     num_procs = comm.Get_size()
# 
#     N = 0
# 
#     # 2. Generación de datos y Broadcast del tamaño N
#     if rank == 0:
#         print("=== PROGRAMA DE CÁLCULO DISTRIBUIDO CON MPI (PYTHON) ===")
#         # En Colab no es interactivo el input clásico si se ejecuta vía mpiexec,
#         # por lo que asignamos un valor fijo o configurable por demostración.
#         N = 100
#         print(f"[Raíz] Tamaño N definido para cada proceso: {N}")
# 
#     # Difundir N desde el proceso raíz (0) a todos los demás procesos
#     N = comm.bcast(N, root=0)
# 
#     # 3. Generación local de valores y cálculo de la suma parcial
#     random.seed(42 + rank)
#     local_sum = sum(random.randint(1, 100) for _ in range(N))
#     print(f"Proceso {rank}: Generó {N} valores. Suma parcial = {local_sum}")
# 
#     # 4. Reducción de la suma (MPI_Reduce)
#     total_sum = comm.reduce(local_sum, op=MPI.SUM, root=0)
# 
#     # 5. Cálculo del promedio global (solo en el proceso raíz)
#     global_average = 0.0
#     if rank == 0:
#         total_elements = N * num_procs
#         global_average = total_sum / total_elements
#         print(f"\n[Raíz] Suma total acumulada: {total_sum}")
#         print(f"[Raíz] Elementos totales procesados: {total_elements}")
#         print(f"[Raíz] Promedio global calculado: {global_average:.4f}\n")
# 
#     # 6. Distribución del promedio a todos los procesos usando Bcast
#     global_average = comm.bcast(global_average, root=0)
# 
#     # 7. Visualización del resultado en cada proceso
#     print(f"Proceso {rank} recibe el promedio global: {global_average:.4f}")
# 
# if __name__ == "__main__":
#     main()

!mpiexec --allow-run-as-root --oversubscribe -np 4 python calculo_mpi.py